{
 "title": "Datastore Celery",
 "description": "Basic celery monitoring example",
 "tags": [
  "celery",
  "datastore"
 ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Celery Worker Status",
   "type": "status-history",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flower_worker_online", "legendFormat": "{{ worker }}" }
   ]
  },
  {
   "title": "Number of Tasks Currently Executing at Worker",
   "type": "graph",
   "description": "This panel shows number of tasks currently executing at worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Average Task Runtime at Worker",
   "type": "timeseries",
   "description": "This panel shows average task runtime at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(avg(rate(flower_task_runtime_seconds_sum[1m]) / rate(flower_task_runtime_seconds_count[1m])) by(task))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Prefetch Time at Worker",
   "type": "graph",
   "description": "This panel shows task prefetch time at worker by worker and task name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flower_task_prefetch_time_seconds",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Number of Tasks Prefetched At Worker",
   "type": "graph",
   "description": "This panel shows number of tasks prefetched at worker by task and worker name.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flower_worker_prefetched_tasks", "legendFormat": "{{task}}, {{worker}}" }
   ]
  },
  {
   "title": "Task Success Ratio",
   "type": "gauge",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-succeeded\"}[1m])) by (task)  / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[1m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Task Failure Ratio",
   "type": "timeseries",
   "description": "This panel presents average task failure ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg(flower_events_total{type=\"task-failed\"}))",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Globale Task Success Ratio",
   "type": "gauge",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum(avg_over_time(flower_events_total{type=\"task-succeeded\"}[15m])) by (task)  / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[15m])) by (task)) * 100)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Current Task Count",
   "type": "stat",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flower_worker_number_of_currently_executing_tasks)",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Worker Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(log_level) (rate({compose_service=~\"worker\"} != `Refusing to deserialize disabled content of type pickle (application/x-python-serialize)` != `Connected to redis` != `mingle: ` !~ `celery@*. ready` | pattern `[<date> <time>: <log_level>/<process>] <task> <function_name>[<task_id>] <msg>` | msg != `` [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WORKER",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "{compose_service=~\"worker\"} != `Refusing to deserialize disabled content of type pickle (application/x-python-serialize)` != `Connected to redis` != `mingle: ` !~ `celery@*. ready` | pattern `[<date> <time>,<ms>: <log_level>/<process>] <task> <function_name>[<task_id>] <msg>` | msg != `` | line_format \"## {{.time}}\\t {{.log_level}}\\t {{.function_name}} :\\n{{.msg}}\""
    }
   ]
  }
 ]
}