{
 "title": "Datastore API",
 "tags": [
  "api",
  "datastore"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fastapi_requests_total{app_name=\"API\", path!=\"/metrics\"})"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_duration_seconds_sum{app_name=\"API\", path!=\"/metrics\"} / fastapi_requests_duration_seconds_count{app_name=\"API\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_exceptions_total{app_name=\"API\"}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"API\", status_code=~\"2.*\", path!=\"/metrics\"}) / sum by(path) (fastapi_responses_total{app_name=\"API\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(path) (fastapi_responses_total{app_name=\"API\", status_code=~\"5.*\", path!=\"/metrics\"}) / sum by(path) (fastapi_responses_total{app_name=\"API\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(fastapi_requests_duration_seconds_bucket{app_name=\"API\", path!=\"/metrics\"}[1m])) by(app_name, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(fastapi_requests_in_progress{app_name=\"API\", path!=\"/metrics\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(fastapi_requests_total{app_name=\"API\" , path!=\"/metrics\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration Per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(fastapi_requests_duration_seconds_bucket{app_name=\"API\", path!=\"/metrics\"}[1m])) by(path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request In Process Per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "fastapi_requests_in_progress{app_name=\"API\", path!=\"/metrics\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec Per Route",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(fastapi_requests_total{app_name=\"API\" , path!=\"/metrics\"}[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fastapi_requests_total{app_name=\"API\", path!=\"/metrics\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\"api\"} != `Started server process` != `Application startup complete` != `Waiting for application startup.` != `Uvicorn running on http://0.0.0.0:3251 (Press CTRL+C to quit)` != `Started parent process` | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | msg != `` |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "{compose_service=~\"api*\"} != `Started server process` != `Application startup complete` != `Waiting for application startup.` != `Uvicorn running on http://0.0.0.0:3251 (Press CTRL+C to quit)` != `Started parent process`| pattern `<date> <time>,<ms> <levelname> [<name>] [<filename>:<lineno>] [trace_id=<otelTraceID> span_id=<otelSpanID> resource.service.name=<otelServiceName>] - <message>` | message!= `` | line_format \"## {{.time}}\\t{{.levelname}}\\n{{.message}} {{.code}}\" |= \"$log_keyword\""
    }
   ]
  },
  {
   "title": "Worker Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(log_level) (rate({compose_service=~\"worker\"} != `Refusing to deserialize disabled content of type pickle (application/x-python-serialize)` != `Connected to redis` != `mingle: ` !~ `celery@*. ready` | pattern `[<date> <time>: <log_level>/<process>] <task> <function_name>[<task_id>] <msg>` | msg != `` |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "WORKER",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "{compose_service=~\"worker\"} != `Refusing to deserialize disabled content of type pickle (application/x-python-serialize)` != `Connected to redis` != `mingle: ` !~ `celery@*. ready` | pattern `[<date> <time>,<ms>: <log_level>/<process>] <task> <function_name>[<task_id>] <msg>` | msg != `` | line_format \"## {{.time}}\\t {{.log_level}}\\t {{.function_name}} :\\n{{.msg}}\""
    }
   ]
  }
 ]
}